# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_occurrences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrences',
            name='end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='occurrences',
            name='start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
