# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180618_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrences',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='occurrences',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
